### ISSUE TITLE
Key not found: apps

### ISSUE THREAD

**Issue by yochananmarqos** [nning/protonutils#2]
```
❯ protonutils list
Warning: Several Steam users available, using XXXXXXXX
All available users: XXXXXXXX, ac
Option "-u" can be used to specify user

Key not found: apps
```
What happened here?

```
❯ protonutils version
1.2.1 20211114014208 https://github.com/nning/protonutils/tree/1.2.1
```

**Comment by nning** [comment]
Did you use a fresh Steam installation? Or did you ever start a game with Steam Play in that installation?

`protonutils` currently does not assume that every game uses the configured default Proton version if *Enable Steam Play for all other titles* is activated. I think it should still be necessary to run a game with Steam Play at least once.

Steam Play titles are gathered from 2 different sources:
* the `CompatToolMapping` in `config/config.vdf`,
* and the `apps` in `userdata/<uid>/config/localconfig.vdf`.

In your case, the latter source does not work, because it seems that Steam did not write any entries to the `apps` key in that config, yet. (In there, it saves stuff like last played timestamp, play time, EULA acceptance, and whether you saw a Steam Play "warning" for that game.)

I prepared a fix in #3; could you please test whether that works for you?

(CI compiled a [binary that you could use][0].)

[0]: https://github.com/nning/protonutils/suites/4348815101/artifacts/114105363

**Comment by yochananmarqos** [comment]
Yes, applying #3 worked. Thanks.

```
❯ protonutils list
Warning: Several Steam users available, using XXXXXXXX
All available users: XXXXXXXX, ac
Option "-u" can be used to specify user

Proton-6.21-GE-1
	Bright Memory: Infinite
	The Elder Scrolls V: Skyrim Special Edition

proton_5
	Resident Evil
	Resident Evil 0

proton_63 (Default)
	Resident Evil 6
```

**Comment by nning** [comment]
Perfect! Thanks for reporting and also thanks for your contribution to the PKGBUILD in the AUR!
