### ISSUE TITLE
Does not find games on the micro SD card on Steam Deck

### ISSUE THREAD

**Issue by sevansup** [nning/protonutils#32]
I tried manually specifying the SD card by running 
./protonutils config steam_root "/run/media/mmcblk0p1/"

However, this did not work as only the steamapps folder can be found at this location, and it was expecting to find the config and userdata folders.

Would be great to use this on Steam Deck to help clean up unused compatdata folders but currently only seems to work for things installed on the internal SSD.

**Comment by nning** [comment]
Currently, the Steam Deck is not supported, because `protonutils` filters by the `ViewedSteamPlay` property to list games efficiently but this property is only set by Desktop Linux Steam and not by the Steam Deck. I made a quick check whether it would work to omit this filtering but I am not happy with the performance. However, I will commit and push that check with an option flag in the next days and then you should be able to test on your Deck.

**Comment by nning** [comment]
I merged changes that should fix finding games on the Steam Deck, please test the latest release (v1.6.3):
https://github.com/nning/protonutils/releases/latest/download/protonutils

**Comment by nning** [comment]
Closing this issue, fix works on my Steam Deck
